title: "Devika Passi | Data & Dashboards"
description: "Turning Data into Stories with SQL, Excel, Power BI, and Python."
url: "https://devika-pss.github.io"
baseurl: "/portfolio"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-remote-theme

seo:
  title: nil

header_pages:
  - about.md
  - projects.md
  - skills.md
  - contact.md

author:
  name   : "Devika Passi"
  links:
    - label: "About Me"
      url: "/portfolio/about/"
    - label: "Projects"
      url: "/portfolio/projects/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/devika-pss"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/your-profile"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:youremail@example.com"


title: "Devika Passi | Data & Dashboards"
tagline: "Data Analyst Portfolio"
