
title: "Devika's Data Analytics Portfolio"
description: "A collection of projects where I dig into data and share what I find."
baseurl: "" 
url: "https://devika-pss.github.io/"

# Theme
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
  - jekyll-seo-tag

# Navigation links
navbar-links:
  Home: "/"
  Projects: "/projects"
  About: "/about"
  Contact: "/contact"

# Author info
author:
  name: "Devika Passi"
  email: "mailto:devikapassi19@gmail.com"
  github: "your-github-username"
