title: "Devika Passi | Data & Dashboards"
description: "Turning Data into Stories with SQL, Excel, Power BI, and Python."
url: "https://devika-pss.github.io"
baseurl: "/portfolio"

remote_theme: mistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-remote-theme

seo:
  title: nil

author:
  name: "Devika"
  links:
    - label: "GitHub"
      url: "https://github.com/devika-pss"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/devika-passi/"
    - label: "Email"
      url: "mailto:devikapassi19@gmail.com"


title: "Devika Passi | Data & Dashboards"
tagline: "Data Analyst Portfolio"
