
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: "Devika's Data Analytics Portfolio"
description: "A collection of projects where I dig into data and share what I find."

# Navigation
header_pages:
  - about.md
  - projects.md
  - skills.md
  - contact.md

# Social links
author:
  name: "Devika Passi"
  links:
    - label: "GitHub"
      url: "https://github.com/your-username"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/devika-passi/"
    - label: "Email"
      url: "mailto:devikapassi19@gmail.com"
